# This file was generated by GoReleaser. DO NOT EDIT.
cask "jqweb" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "7d8bda10abbba74b2adc7a8fc13c0f0142f53ad7af90599b21a24f27ba2301db"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "50c088ae5cc746abba5b6db1dac712cbaae1df072ca9c2d660feb307f237eedc"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "7bec46bd949f6b68c30b78ef755b7579b0a122ceed45f4832557f0526fa2252d"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "4a017f1611aaba8086dd9240b4bb85d9cc6c96638361eec8c306868806f2ca96"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jqweb"
  desc "Renders JSON like jq, but as a webpage"
  homepage "https://github.com/zafnz/jqweb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jqweb"

  # No zap stanza required
end
