# This file was generated by GoReleaser. DO NOT EDIT.
cask "jqweb" do
  version "0.4.0"

  on_macos do
    on_arm do
      sha256 "26e7749f6cec7240e0783f0cc5ee91aedb227571f27bcdcc59860d13f93e40df"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b5b1b829345f5a6c9868b9034efef846c8146f5ccef54e433504682a125d47a7"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0bdb1ad827b4985e0010fe4f9ed5fcc389cef3d4a8432d0fdcc89e5acf0e1232"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "bce8cb7dd4a97844bac97ed4ca007a4836f4e0c7b6c1bc1cfbf4437292f1f103"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jqweb"
  desc "Renders JSON like jq, but as a webpage"
  homepage "https://github.com/zafnz/jqweb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jqweb"

  # No zap stanza required
end
