# This file was generated by GoReleaser. DO NOT EDIT.
cask "jqweb" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "eae90a577e074ed460c01059c6647cdae35cddbd2d28b51f314b65dbc87037f5"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b7eb41539738dd34ad80d5a6bb7f1c3e8edcaaa0e3ce88e00c43c58d6ce7a207"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1af01fe4178e80274c9a5823facd6b2e53444105eb0b7d0a0ca5a6a07bcb7e3c"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "958db770a1b3969639d4f75861facda6223fe122f811b5b7112e7bef63f7def4"
      url "https://github.com/zafnz/jqweb/releases/download/v#{version}/jqweb_#{version}_linux_amd64.tar.gz"
    end
  end

  name "jqweb"
  desc "Renders JSON like jq, but as a webpage"
  homepage "https://github.com/zafnz/jqweb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jqweb"

  # No zap stanza required
end
